spring.application.name=mypackage

spring.datasource.url=jdbc:mysql://localhost:3306/db_student_app?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MySql123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=3000